### ISSUE TITLE
Limit job-pool size

### ISSUE THREAD

**Issue by Dash83** [rust-threadpool/rust-threadpool#102]
It would be great if we could set a maximum number of queued jobs for the pool. In this case, adding a new job to a full pool would return an error.

**Comment by dns2utf8** [comment]
Would you use that to implement back-pressure?

**Comment by dns2utf8** [comment]
As a workaround for now you could implement a function that checks the queue size before submitting a new job.

I [implemented an example for you](https://play.rust-lang.org/?gist=98e3b9977c23c656788be36cca1f9477&version=stable&mode=debug&edition=2018).

**Comment by Dash83** [comment]
Thank you, that's exactly what I ended up doing in my code.

**Comment by dns2utf8** [comment]
For 2.0, I plan give people the option to choose the channel they use adding support to bounded channels.
Leaving this open for now.

**Comment by dns2utf8** [comment]
Actually, this might get implemented with #104 -> Closing for now.
Feel free to open it again
