### ISSUE TITLE
Shutdown threads gracefully

### ISSUE THREAD

**Issue by jeprojects** [rust-threadpool/rust-threadpool#103]
Is there a way to shutdown the threads when they have finished their current job?

**Comment by dns2utf8** [comment]
Hi @jeprojects 

Yes the most generic way is to use this code:
```rust
let pool = Builder::new().build()
// ... spawn all the work with pool.execute(...)

// here you don't need the pool anymore
pool.join();
drop(pool);
```

Does this answer your question?

Cheers,
Stefan

**Comment by jeprojects** [comment]
If the pool was in the middle of a task, wouldn't that force close the thread?

**Comment by dns2utf8** [comment]
No because the `pool.join()` awaits the the last tasks finish.
Then once the pool gets dropped the workers receive a signal and terminate themselves.

**Comment by dns2utf8** [comment]
I hope, I answered you question.
If not, feel free to reopen this or a new issue.

Cheers,
Stefan
