### ISSUE TITLE
libz bliz tracking issues

### ISSUE THREAD

**Issue by ericho** [rust-threadpool/rust-threadpool#86]
Issues filed based on information from https://public.etherpad-mozilla.org/p/rust-api-guidelines-threadpool

- [ ] [Missing categories and keywords in Cargo.toml](https://github.com/rust-threadpool/rust-threadpool/issues/84)
- [ ] [Missing hyperlinks in documentation](https://github.com/rust-threadpool/rust-threadpool/issues/85)

**Comment by KodrAus** [comment]
Looks like these are all sorted! :tada: Thanks @ericho and @mjkillough!

**Comment by frewsxcv** [comment]
Thanks everyone!
