### ISSUE TITLE
Feature: split thread pool from work queue

### ISSUE THREAD

**Issue by Diggsey** [rust-threadpool/rust-threadpool#94]
This library (and the others like it) combine the notion of a "replenishing pool of N threads" with a "work queue". It would be useful to expose these building blocks separately.

The raw thread pool would allow you to run any `Send + Sync + Fn` type across N threads, and would automatically restart a thread if it panicked. The work queue would be an implementation of that function which pulled jobs from a queue and executed them.

**Comment by dns2utf8** [comment]
Hi @Diggsey 

Sorry for the late reply. I struggle to understand your request. 

For the work queue you could use [channel](https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html) or [sync_channel](https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html) directly.

I am closing this issue for now. Feel free to open it again.

Cheers,
Stefan
