### ISSUE TITLE
Hardcoded constant in example

### ISSUE THREAD

**Issue by nico-abram** [rust-threadpool/rust-threadpool#98]
https://docs.rs/threadpool/1.7.1/threadpool/#synchronized-with-a-barrier

I feel like the 23 in the assert at the end should be n_jobs.

**Comment by dns2utf8** [comment]
Hi

Yes this is true. If I recall correctly I put the explicit number in the docs to show the exact result.
I would also be fine if you added a comment or replace it with the name and send it as a pull request.

Best,
Stefan

**Comment by dns2utf8** [comment]
It is explained in #99 
Closing this for now. Feel free to reopen.

Cheers,
Stefan

**Comment by dns2utf8** [comment]
bors: close
